### ISSUE TITLE
无法在Minecraft 1.6.4中工作

### ISSUE THREAD

**Issue by CJYKK** [CFPAOrg/I18nUpdateMod3#14]
无法在Minecraft 1.6.4中工作，安装Mod后无法启动，日志报错：
```
2023-08-28 16:16:10 [INFO] [STDOUT] [2023-08-28 16:16:10] [INFO]: I18nUpdate Mod is loaded in 1.6.4 with Forge
2023-08-28 16:16:10 [INFO] [STDERR] !![Fatal]!Exception caught from launcher
2023-08-28 16:16:10 [INFO] [STDERR] java.lang.NoClassDefFoundError: org/apache/commons/codec/digest/DigestUtils
2023-08-28 16:16:10 [INFO] [STDERR] 	at i18nupdatemod.core.ResourcePack.isUpToDate(ResourcePack.java:60)
2023-08-28 16:16:10 [INFO] [STDERR] 	at i18nupdatemod.core.ResourcePack.checkUpdate(ResourcePack.java:38)
2023-08-28 16:16:10 [INFO] [STDERR] 	at i18nupdatemod.I18nUpdateMod.init(I18nUpdateMod.java:36)
2023-08-28 16:16:10 [INFO] [STDERR] 	at i18nupdatemod.launchwrapper.LaunchWrapperTweaker.acceptOptions(LaunchWrapperTweaker.java:23)
2023-08-28 16:16:10 [INFO] [STDERR] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:110)
2023-08-28 16:16:10 [INFO] [STDERR] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2023-08-28 16:16:10 [INFO] [STDERR] 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
2023-08-28 16:16:10 [INFO] [STDERR] 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
2023-08-28 16:16:10 [INFO] [STDERR] 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
2023-08-28 16:16:10 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.digest.DigestUtils
2023-08-28 16:16:10 [INFO] [STDERR] 	at java.net.URLClassLoader.findClassInternal(URLClassLoader.java:401)
2023-08-28 16:16:10 [INFO] [STDERR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
2023-08-28 16:16:10 [INFO] [STDERR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:427)
2023-08-28 16:16:10 [INFO] [STDERR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
2023-08-28 16:16:10 [INFO] [STDERR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:360)
2023-08-28 16:16:10 [INFO] [STDERR] 	... 9 more
2023-08-28 16:16:10 [INFO] [STDERR] !![Fatal]!Exiting with ERROR
``` 

环境信息：
```
-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_382, Alibaba
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Alibaba
	Memory: 1334665560 bytes (1272 MB) / 1488453632 bytes (1419 MB) up to 15271460864 bytes (14564 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 0 loaded mod(s)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx16384m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v8.11 FML v6.4.50.1,345 Minecraft Forge 9.11.1.1345 Optifine OptiFine_1.6.4_HD_U_D1 3 mods loaded, 3 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FML{6.4.50.1,345} [Forge Mod Loader] (forge-1.6.4-9.11.1.1345-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forge{9.11.1.1345} [Minecraft Forge] (forge-1.6.4-9.11.1.1345-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Launched Version: 1.6.4
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.99, NVIDIA Corporation
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Pack: Default
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
```

**Comment by 3093FengMing** [comment]
被确定的

**Comment by xfl03** [comment]
应该是1.6.4没有DigestUtils，这个确实得自己实现一下

**Comment by xfl03** [comment]
已经在3.5.2中修复这一问题
