### ISSUE TITLE
在Minecraft 1.6.4中安装导致崩溃

### ISSUE THREAD

**Issue by woodzn** [CFPAOrg/I18nUpdateMod3#20]
在Crash Landing整合包中安装自动汉化，启动直接崩溃，pcl的日志如下，安装前可以启动，运行没有问题
```
四月 07, 2024 2:04:12 上午 net.minecraft.launchwrapper.LogWrapper log
信息: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
四月 07, 2024 2:04:12 上午 net.minecraft.launchwrapper.LogWrapper log
信息: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
四月 07, 2024 2:04:12 上午 net.minecraft.launchwrapper.LogWrapper log
信息: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
2024-04-07 02:04:12 [信息] [ForgeModLoader] Forge Mod Loader version 6.4.49.965 for Minecraft 1.6.4 loading
2024-04-07 02:04:12 [信息] [ForgeModLoader] Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_51, running on Windows 8:amd64:6.2, installed at D:\Program Files\Java\jre7
2024-04-07 02:04:12 [警告] [ForgeModLoader] The coremod net.minecraftforge.lex.sortfix.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-04-07 02:04:12 [警告] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-04-07 02:04:12 [信息] [ForgeModLoader] Loading tweaker i18nupdatemod.launchwrapper.LaunchWrapperTweaker from [自动汉化更新] I18nUpdateMod-3.5.3-all.jar
2024-04-07 02:04:12 [警告] [ForgeModLoader] The coremod appeng.transformer.AppEngCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-04-07 02:04:12 [信息] [ForgeModLoader] [AppEng] Core Init
2024-04-07 02:04:12 [警告] [ForgeModLoader] The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-04-07 02:04:13 [警告] [ForgeModLoader] The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-04-07 02:04:13 [警告] [ForgeModLoader] The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-04-07 02:04:13 [警告] [ForgeModLoader] The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-04-07 02:04:13 [警告] [ForgeModLoader] The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-04-07 02:04:13 [警告] [ForgeModLoader] The coremod openmods.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-04-07 02:04:13 [警告] [ForgeModLoader] The coremod squeek.spiceoflife.asm.ASMPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-04-07 02:04:13 [警告] [ForgeModLoader] The coremod tconstruct.preloader.TConstructLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-04-07 02:04:13 [信息] [TCon-Preloader] Scalpel. Suction. Lumber axe. CLEAR! *zap*
2024-04-07 02:04:13 [信息] [TCon-Preloader] Constructing preloader (Modules: [tconstruct.preloader.AccessTransformers, tconstruct.preloader.ASMInterfaceRepair])
2024-04-07 02:04:13 [信息] [TCon-Preloader] Found a properties file. Attempting load...
2024-04-07 02:04:13 [信息] [TCon-Preloader] Loaded properties successfully. Using specified settings.
2024-04-07 02:04:13 [信息] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2024-04-07 02:04:13 [信息] [ForgeModLoader] Loading tweak class name i18nupdatemod.launchwrapper.LaunchWrapperTweaker
2024-04-07 02:04:13 [信息] [STDERR] Exception in thread "main" java.lang.reflect.InvocationTargetException
2024-04-07 02:04:13 [信息] [STDERR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-04-07 02:04:13 [信息] [STDERR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.lang.reflect.Method.invoke(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
2024-04-07 02:04:13 [信息] [STDERR] 	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
2024-04-07 02:04:13 [信息] [STDERR] Caused by: java.lang.UnsupportedClassVersionError: i18nupdatemod/launchwrapper/LaunchWrapperTweaker : Unsupported major.minor version 52.0
2024-04-07 02:04:13 [信息] [STDERR] 	at java.lang.ClassLoader.defineClass1(Native Method)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.lang.ClassLoader.defineClass(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.security.SecureClassLoader.defineClass(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.net.URLClassLoader.defineClass(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.net.URLClassLoader.access$100(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.net.URLClassLoader$1.run(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.net.URLClassLoader$1.run(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.net.URLClassLoader.findClass(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.lang.ClassLoader.loadClass(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.lang.ClassLoader.loadClass(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:102)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.lang.ClassLoader.loadClass(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.lang.ClassLoader.loadClass(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.lang.Class.forName0(Native Method)
2024-04-07 02:04:13 [信息] [STDERR] 	at java.lang.Class.forName(Unknown Source)
2024-04-07 02:04:13 [信息] [STDERR] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
2024-04-07 02:04:13 [信息] [STDERR] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2024-04-07 02:04:13 [信息] [STDERR] 	... 6 more
```
使用的是java7 7.0.51 64位

**Comment by xfl03** [comment]
这……不支持Java 7的啊，用Java 8就行

**Comment by woodzn** [comment]
可是我用java8也是直接游戏崩溃
